### ISSUE TITLE
Ошибка при поиске ассоциата

### ISSUE THREAD

**Issue by Nikis14** [nikitaodnorob/rap-paraphraser-backend#1]
Если попытаться найти ассоциат для слова "рекомендованный", то ответ не загрузится. В консоли браузера высвечивается ошибка _"Uncaught (in promise) SyntaxError"_. Возможно, этого слова нет в словаре модели.

**Comment by nikitaodnorob** [comment]
Эта ошибка относится к фронтенду, перенесено сюда: https://github.com/nikitaodnorob/rap-paraphraser/issues/164
